In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import os
import glob
%matplotlib inline 

In [19]:
a = pd.read_excel('deneme.xlsx')

In [20]:
a.head()

Time (s)      Channel 1 (V)      Channel 2 (V)
0   -1.00000   1484323004216500  14807953575108700
1   -0.99975   1484661681938600  14811280287198800
2   -0.99950   1484661681938600   1481460699928900
3   -0.99925  14850003596607000   1481460699928900
4 -999.00000  14850003596607000   1481460699928900

In [21]:
a.columns

Index(['Time (s)', 'Channel 1 (V)', 'Channel 2 (V)'], dtype='object')

In [22]:
a['Time (s)'] = a['Time (s)'].astype(float)


In [23]:
a.loc[(a['Time (s)'] >= 0)]

Time (s)      Channel 1 (V)      Channel 2 (V)
4000    0.00000   1484323004216500  14857854256460900
4001    0.00025   1484323004216500  14857854256460900
4002    0.00050   1484323004216500  14861180968551100
4003    0.00075   1484661681938600  14861180968551100
4004    1.00000   1484661681938600  14861180968551100
...         ...                ...                ...
7995    0.99875  14829682933281000    148013001509284
7996  999.00000  14836456487723000    148013001509284
7997    0.99925  14836456487723000  14804626863018500
7998    0.99950  14839843264944000  14804626863018500
7999    0.99975  14839843264944000  14807953575108700

[4000 rows x 3 columns]

In [105]:
#importing data csv files
egerest = glob.glob('dataege/rest/*.csv')
#Reorder
egerestdf = pd.concat([pd.read_csv(f, sep = ",", skiprows= 10) for f in egerest], ignore_index = True)
egerestdf = egerestdf.loc[(df['Time (s)'] >= 0)]
egerestdf.rename(columns = {'Time (s)':'Time', 'Channel 1 (V)':'Channel1','Channel 2 (V)':'Channel2'}, inplace = True)
egerestdf['Class'] = 'Rest'
egerestdf['Participant'] = 'Ege'


egeyumruk = glob.glob('dataege/yumruk/*.csv')
#Let's check the number of txt files
egeyumrukdf = pd.concat([pd.read_csv(f, sep = ",", skiprows= 10) for f in egeyumruk], ignore_index = True)
egeyumrukdf = egeyumrukdf.loc[(df['Time (s)'] >= 0)]
egeyumrukdf.rename(columns = {'Time (s)':'Time', 'Channel 1 (V)':'Channel1','Channel 2 (V)':'Channel2'}, inplace = True)
egeyumrukdf['Class'] = 'Yumruk'
egeyumrukdf['Participant'] = 'Ege'

egeeldisari = glob.glob('dataege/eldisari/*.csv')
#Let's check the number of txt files
egeeldisaridf = pd.concat([pd.read_csv(f, sep = ",", skiprows= 10) for f in egeeldisari], ignore_index = True)
egeeldisaridf = egeeldisaridf.loc[(df['Time (s)'] >= 0)]
egeeldisaridf.rename(columns = {'Time (s)':'Time', 'Channel 1 (V)':'Channel1','Channel 2 (V)':'Channel2'}, inplace = True)
egeeldisaridf['Class'] = 'El Disari'
egeeldisaridf['Participant'] = 'Ege'

egeelyukari = glob.glob('dataege/elyukari/*.csv')
#Let's check the number of txt files
egeelyukaridf = pd.concat([pd.read_csv(f, sep = ",", skiprows= 10) for f in egeelyukari], ignore_index = True)
egeelyukaridf = egeelyukaridf.loc[(df['Time (s)'] >= 0)]
egeelyukaridf.rename(columns = {'Time (s)':'Time', 'Channel 1 (V)':'Channel1','Channel 2 (V)':'Channel2'}, inplace = True)
egeelyukaridf['Class'] = 'El Yukari'
egeelyukaridf['Participant'] = 'Ege'

egeeliceri = glob.glob('dataege/eliceri/*.csv')
#Let's check the number of txt files
egeeliceridf = pd.concat([pd.read_csv(f, sep = ",", skiprows= 10) for f in egeeliceri], ignore_index = True)
egeeliceridf = egeeliceridf.loc[(df['Time (s)'] >= 0)]
egeeliceridf.rename(columns = {'Time (s)':'Time', 'Channel 1 (V)':'Channel1','Channel 2 (V)':'Channel2'}, inplace = True)
egeeliceridf['Class'] = 'El Iceri'
egeeliceridf['Participant'] = 'Ege'

egeicebukme = glob.glob('dataege/icebukme/*.csv')
#Let's check the number of txt files
egeicebukmedf = pd.concat([pd.read_csv(f, sep = ",", skiprows= 10) for f in egeicebukme], ignore_index = True)
egeicebukmedf = egeicebukmedf.loc[(df['Time (s)'] >= 0)]
egeicebukmedf.rename(columns = {'Time (s)':'Time', 'Channel 1 (V)':'Channel1','Channel 2 (V)':'Channel2'}, inplace = True)
egeicebukmedf['Class'] = 'Ice Bukme'
egeicebukmedf['Participant'] = 'Ege'


#Kaan
kaanrest = glob.glob('datakaan/rest/*.csv')
#Reorder
kaanrestdf = pd.concat([pd.read_csv(f, sep = ",", skiprows= 10) for f in kaanrest], ignore_index = True)
kaanrestdf = kaanrestdf.loc[(df['Time (s)'] >= 0)]
kaanrestdf.rename(columns = {'Time (s)':'Time', 'Channel 1 (V)':'Channel1','Channel 2 (V)':'Channel2'}, inplace = True)
kaanrestdf['Class'] = 'Rest'
kaanrestdf['Participant'] = 'Kaan'

kaanyumruk = glob.glob('datakaan/yumruk/*.csv')
#Reorder
kaanyumrukdf = pd.concat([pd.read_csv(f, sep = ",", skiprows= 10) for f in kaanyumruk], ignore_index = True)
kaanyumrukdf = kaanyumrukdf.loc[(df['Time (s)'] >= 0)]
kaanyumrukdf.rename(columns = {'Time (s)':'Time', 'Channel 1 (V)':'Channel1','Channel 2 (V)':'Channel2'}, inplace = True)
kaanyumrukdf['Class'] = 'Yumruk'
kaanyumrukdf['Participant'] = 'Kaan'

kaaneldisari = glob.glob('datakaan/eldisari/*.csv')
#Reorder
kaaneldisaridf = pd.concat([pd.read_csv(f, sep = ",", skiprows= 10) for f in kaaneldisari], ignore_index = True)
kaaneldisaridf = kaaneldisaridf.loc[(df['Time (s)'] >= 0)]
kaaneldisaridf.rename(columns = {'Time (s)':'Time', 'Channel 1 (V)':'Channel1','Channel 2 (V)':'Channel2'}, inplace = True)
kaaneldisaridf['Class'] = 'El Disari'
kaaneldisaridf['Participant'] = 'Kaan'

kaanelyukari = glob.glob('datakaan/elyukari/*.csv')
#Reorder
kaanelyukaridf = pd.concat([pd.read_csv(f, sep = ",", skiprows= 10) for f in kaanelyukari], ignore_index = True)
kaanelyukaridf = kaanelyukaridf.loc[(df['Time (s)'] >= 0)]
kaanelyukaridf.rename(columns = {'Time (s)':'Time', 'Channel 1 (V)':'Channel1','Channel 2 (V)':'Channel2'}, inplace = True)
kaanelyukaridf['Class'] = 'El Yukari'
kaanelyukaridf['Participant'] = 'Kaan'

kaanicebukme = glob.glob('datakaan/icebukme/*.csv')
#Reorder
kaanicebukmedf = pd.concat([pd.read_csv(f, sep = ",", skiprows= 10) for f in kaanicebukme], ignore_index = True)
kaanicebukmedf = kaanicebukmedf.loc[(df['Time (s)'] >= 0)]
kaanicebukmedf.rename(columns = {'Time (s)':'Time', 'Channel 1 (V)':'Channel1','Channel 2 (V)':'Channel2'}, inplace = True)
kaanicebukmedf['Class'] = 'Ice Bukme'
kaanicebukmedf['Participant'] = 'Kaan'

kaaneliceri = glob.glob('datakaan/eliceri/*.csv')
#Reorder
kaaneliceridf = pd.concat([pd.read_csv(f, sep = ",", skiprows= 10) for f in kaanicebukme], ignore_index = True)
kaaneliceridf = kaaneliceridf.loc[(df['Time (s)'] >= 0)]
kaaneliceridf.rename(columns = {'Time (s)':'Time', 'Channel 1 (V)':'Channel1','Channel 2 (V)':'Channel2'}, inplace = True)
kaaneliceridf['Class'] = 'El Iceri'
kaaneliceridf['Participant'] = 'Kaan'


#SEVDE
sevderest = glob.glob('datasevde/rest/*.csv')
#Reorder
sevderestdf = pd.concat([pd.read_csv(f, sep = ",", skiprows= 10) for f in sevderest], ignore_index = True)
sevderestdf = sevderestdf.loc[(df['Time (s)'] >= 0)]
sevderestdf.rename(columns = {'Time (s)':'Time', 'Channel 1 (V)':'Channel1','Channel 2 (V)':'Channel2'}, inplace = True)
sevderestdf['Class'] = 'Rest'
sevderestdf['Participant'] = 'Sevde'


sevdeyumruk = glob.glob('datasevde/yumruk/*.csv')
#Reorder
sevdeyumrukdf = pd.concat([pd.read_csv(f, sep = ",", skiprows= 10) for f in sevdeyumruk], ignore_index = True)
sevdeyumrukdf = sevdeyumrukdf.loc[(df['Time (s)'] >= 0)]
sevdeyumrukdf.rename(columns = {'Time (s)':'Time', 'Channel 1 (V)':'Channel1','Channel 2 (V)':'Channel2'}, inplace = True)
sevdeyumrukdf['Class'] = 'Yumruk'
sevdeyumrukdf['Participant'] = 'Sevde'


sevdeeldisari = glob.glob('datasevde/eldisari/*.csv')
#Reorder
sevdeeldisaridf = pd.concat([pd.read_csv(f, sep = ",", skiprows= 10) for f in sevdeeldisari], ignore_index = True)
sevdeeldisaridf = sevdeeldisaridf.loc[(df['Time (s)'] >= 0)]
sevdeeldisaridf.rename(columns = {'Time (s)':'Time', 'Channel 1 (V)':'Channel1','Channel 2 (V)':'Channel2'}, inplace = True)
sevdeeldisaridf['Class'] = 'El Disari'
sevdeeldisaridf['Participant'] = 'Sevde'


sevdeelyukari = glob.glob('datasevde/elyukari/*.csv')
#Reorder
sevdeelyukaridf = pd.concat([pd.read_csv(f, sep = ",", skiprows= 10) for f in sevdeelyukari], ignore_index = True)
sevdeelyukaridf = sevdeelyukaridf.loc[(df['Time (s)'] >= 0)]
sevdeelyukaridf.rename(columns = {'Time (s)':'Time', 'Channel 1 (V)':'Channel1','Channel 2 (V)':'Channel2'}, inplace = True)
sevdeelyukaridf['Class'] = 'El Yukari'
sevdeelyukaridf['Participant'] = 'Sevde'

sevdeicebukme = glob.glob('datasevde/icebukme/*.csv')
#Reorder
sevdeicebukmedf = pd.concat([pd.read_csv(f, sep = ",", skiprows= 10) for f in sevdeicebukme], ignore_index = True)
sevdeicebukmedf = sevdeicebukmedf.loc[(df['Time (s)'] >= 0)]
sevdeicebukmedf.rename(columns = {'Time (s)':'Time', 'Channel 1 (V)':'Channel1','Channel 2 (V)':'Channel2'}, inplace = True)
sevdeicebukmedf['Class'] = 'Ice Bukme'
sevdeicebukmedf['Participant'] = 'Sevde'


sevdeeliceri = glob.glob('datasevde/eliceri/*.csv')
#Reorder
sevdeeliceridf = pd.concat([pd.read_csv(f, sep = ",", skiprows= 10) for f in sevdeeliceri], ignore_index = True)
sevdeeliceridf = sevdeeliceridf.loc[(df['Time (s)'] >= 0)]
sevdeeliceridf.rename(columns = {'Time (s)':'Time', 'Channel 1 (V)':'Channel1','Channel 2 (V)':'Channel2'}, inplace = True)
sevdeeliceridf['Class'] = 'El Iceri'
sevdeeliceridf['Participant'] = 'Sevde'


In [106]:
sevdeeliceridf

Time  Channel1  Channel2     Class Participant
4000  0.00000  1.472469  1.487781  El Iceri       Sevde
4001  0.00025  1.473147  1.488114  El Iceri       Sevde
4002  0.00050  1.473147  1.488114  El Iceri       Sevde
4003  0.00075  1.473485  1.488447  El Iceri       Sevde
4004  0.00100  1.473824  1.488779  El Iceri       Sevde
...       ...       ...       ...       ...         ...
7995  0.99875  1.474163  1.476471  El Iceri       Sevde
7996  0.99900  1.474163  1.476471  El Iceri       Sevde
7997  0.99925  1.474163  1.476471  El Iceri       Sevde
7998  0.99950  1.474163  1.476471  El Iceri       Sevde
7999  0.99975  1.474163  1.476471  El Iceri       Sevde

[4000 rows x 5 columns]

In [108]:
reads = [egeelyukaridf, egeeldisaridf, egeyumrukdf, egerestdf,egeeliceridf,egeicebukmedf,kaanrestdf,
        kaanyumrukdf,kaaneldisaridf,kaanelyukaridf,kaanicebukmedf,kaaneliceridf, sevdeyumrukdf,
        sevderestdf,sevdeeldisaridf,sevdeelyukaridf, sevdeicebukmedf,sevdeeliceridf]

In [109]:
df = pd.concat(reads)

In [110]:
df

Time  Channel1  Channel2      Class Participant
4000  0.02000  1.486355  1.461500  El Yukari         Ege
4001  0.02025  1.486016  1.461168  El Yukari         Ege
4002  0.02050  1.486016  1.460835  El Yukari         Ege
4003  0.02075  1.486016  1.461168  El Yukari         Ege
4004  0.02100  1.485678  1.460835  El Yukari         Ege
...       ...       ...       ...        ...         ...
7995  0.99875  1.474163  1.476471   El Iceri       Sevde
7996  0.99900  1.474163  1.476471   El Iceri       Sevde
7997  0.99925  1.474163  1.476471   El Iceri       Sevde
7998  0.99950  1.474163  1.476471   El Iceri       Sevde
7999  0.99975  1.474163  1.476471   El Iceri       Sevde

[133120 rows x 5 columns]

In [111]:
df.isna().sum()


Time           0
Channel1       0
Channel2       0
Class          0
Participant    0
dtype: int64

In [112]:
df.dtypes


Time           float64
Channel1       float64
Channel2       float64
Class           object
Participant     object
dtype: object

In [113]:
print("Value Count :\n", df["Class"].value_counts())


Value Count :
 El Disari    24240
Yumruk       24240
Rest         24160
El Iceri     20160
Ice Bukme    20160
El Yukari    20160
Name: Class, dtype: int64


In [116]:
df1  = df.drop('Time',axis=1, inplace=False)
df2  = df1.drop('Participant',axis=1, inplace=False)
df2

Channel1  Channel2      Class
4000  1.486355  1.461500  El Yukari
4001  1.486016  1.461168  El Yukari
4002  1.486016  1.460835  El Yukari
4003  1.486016  1.461168  El Yukari
4004  1.485678  1.460835  El Yukari
...        ...       ...        ...
7995  1.474163  1.476471   El Iceri
7996  1.474163  1.476471   El Iceri
7997  1.474163  1.476471   El Iceri
7998  1.474163  1.476471   El Iceri
7999  1.474163  1.476471   El Iceri

[133120 rows x 3 columns]

## KNN Classifier

In [117]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix

In [118]:
features=df2.drop(columns=["Class"])
labels=df2["Class"]

In [119]:
X_train, X_test,y_train,y_test= train_test_split(features,labels,test_size=0.30, random_state=1)

In [120]:
#Manhatten
knn=KNeighborsClassifier(metric='minkowski',algorithm= 'auto',n_neighbors=10,p=2,weights='distance',leaf_size=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print("Accuracy", accuracy_score(y_test,y_pred))
print("F1 Score", f1_score(y_test, y_pred, average="macro"))
print("Precision",precision_score(y_test, y_pred, average="macro"))
print("Recall Score", recall_score(y_test, y_pred, average="macro"))
print("Confusion Matrix",confusion_matrix(y_test, y_pred))

Accuracy 0.4782151442307692
F1 Score 0.47549287445543525
Precision 0.4824990187009181
Recall Score 0.4734497590991444
Confusion Matrix [[3998  669  656  437  795  829]
 [ 694 2246  458  846  817  927]
 [ 817  697 2472  299 1174  612]
 [ 554 1374  436 2924  448  322]
 [ 571  552  743  118 4036 1122]
 [ 719  731  506  259 1656 3422]]
